### ISSUE TITLE
Feature use cases on the Wiki

### ISSUE THREAD

**Issue by runasand** [usbarmory/usbarmory#73]
I know some folks are using the USB armory in fun and interesting ways (e.g. GlobaLeaks, Amnesty International). Would be great to feature some of these use cases on the Wiki.

**Comment by abarisani** [comment]
Sure thing, we already list GlobalLeaks [here](https://github.com/usbarmory/usbarmory/wiki/External-resources#projects).

If there are more projects I'd be happy to create a more prominent wiki page, could you email me more information on the specific use cases for a beefier wiki page?

Thanks!
