### ISSUE TITLE
Schematic for USB Armory Mk II

### ISSUE THREAD

**Issue by Kailasamraju** [usbarmory/usbarmory#80]
Hi, 

We would like to request for PDF of the total schematics for USB Armory Mk II. The schematics available on the Git are pertaining to individual components and this is not very helpful for our research. 

Request you to kindly assist us with the total schematics (PDF) and design files at the earliest please. 

Regards.

**Comment by abarisani** [comment]
In case you have commercial requests please contact us at usbarmory@withsecure.com
